bookstore/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path("", BookListView.as_view(), name="index"),
    path("<int:pk>", BookDetailView.as_view(), name="book_detail"),
    path("review/<int:pk>", BookReviewView.as_view(), name="book_review"),
    path("cart", CartView.as_view(), name="cart_item"),
    path("order", CreateOrder.as_view(), name="create_order"),
    path("wishlist", WishlistView.as_view(), name="wishlist"),
    path("otp", OTPConfirmation.as_view(), name="otp_confirmation"),
    path("read_book", ReadBookPDFView.as_view(), name="read_book"),
]

online_bookstore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings
from django.views.generic.base import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),  # new
    path("accounts/", include("django.contrib.auth.urls")),  # new
    path("", include("bookstore.urls")),
    path("books/", include("bookstore.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path

from .views import HomePageView

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
]

bookstore/models.py
from django.urls import reverse
from django.db import models
from django.conf import settings


class Book(models.Model):
    GENRE_CHOICES = (
        ("Fiction", "Fiction"),
        ("Non-Fiction", "Non-Fiction"),
        ("Science Fiction", "Science Fiction"),
        ("Mystery", "Mystery"),
    )

    title = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    genre = models.CharField(max_length=50, choices=GENRE_CHOICES)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField()
    image = models.ImageField()
    avg_rating = models.DecimalField(
        default=0.0,
        max_digits=3,
        decimal_places=2,
        help_text="Average rating gor the book",
    )

    def update_avg_rating(self):
        total_rating = sum(review.rating for review in self.reviews.all())
        num_reviews = self.reviews.count()

        if num_reviews > 0:
            self.avg_rating = total_rating / num_reviews
        else:
            self.avg_rating = 0.0

        self.save()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("book_detail", kwargs={"pk": self.pk})


class BookPDF(models.Model):
    book = models.OneToOneField(Book, on_delete=models.CASCADE, related_name="pdf")
    pdf_file = models.FileField(upload_to="pdf_books/")

    def __str__(self):
        return f"PDF for {self.book.title}"


class Cart(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.user.username


class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    books = models.ForeignKey(Book, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.books.title} in Cart ({self.quantity})"


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    items = models.ManyToManyField(Book, through="OrderItem")
    total_price = models.DecimalField(max_digits=10, decimal_places=2)

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    class Meta:
        unique_together = ("order", "book")


class Wishlist(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.user.username


class WishlistItem(models.Model):
    wishlist = models.ForeignKey(Wishlist, on_delete=models.CASCADE)
    books = models.ForeignKey(Book, on_delete=models.CASCADE)

    class Meta:
        # Adding unique constraint to prevent duplicate entries for a book in a wishlist
        unique_together = ("wishlist", "books")

    def __str__(self):
        return ""


class BookReview(models.Model):
    RATING_CHOICES = [
        (1, "One star"),
        (2, "Two star"),
        (3, "Three star"),
        (4, "Four star"),
        (5, "Five star"),
    ]
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name="reviews")
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    rating = models.IntegerField(choices=RATING_CHOICES)
    review_text = models.TextField()

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.book.update_avg_rating()

    def __str__(self):
        return self.book.title

bookstore/forms.py
from django import forms
from .models import BookReview


class BookReviewForm(forms.ModelForm):
    class Meta:
        model = BookReview
        fields = ["rating", "review_text"]
        widgets = {
            "review_text": forms.Textarea(attrs={"rows": 3}),
        }

bookstore/views.py
import random
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import ListView, DetailView, DeleteView
from django.db.models import Q
from django.contrib import messages
from .forms import BookReviewForm
from .models import *
from accounts.models import CustomUser
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.mail import send_mail


class BookListView(ListView):
    model = Book
    template_name = "index.html"

    def get_queryset(self):
        queryset = super().get_queryset()
        genre = self.request.GET.get("genre")
        query = self.request.GET.get("title")
        if genre:
            queryset = queryset.filter(genre=genre)
        if query:
            queryset = queryset.filter(
                Q(title__icontains=query)
                | Q(author__icontains=query)
                | Q(genre__icontains=query)
            )
        return queryset

    def get_context_data(self):
        context = super().get_context_data()
        context["genres"] = Book.GENRE_CHOICES
        return context


class BookDetailView(DetailView):
    model = Book
    template_name = "book_detail.html"

    def get(self, request, *args, **kwargs):
        book = self.get_object()
        form = BookReviewForm()

        # review, created = BookReview.objects.get_or_create(book=book, user=request.user)
        context = {
            "object": book,
            "form": form,
            # "review": review,
        }

        return render(request, "book_detail.html", context)

    def post(self, request, *args, **kwargs):
        book = self.get_object()
        if "add_to_cart" in request.POST:
            print(book)
            user_cart, created = Cart.objects.get_or_create(user=request.user)
            cart_item, item_created = CartItem.objects.get_or_create(
                cart=user_cart, books=book
            )
            if not item_created:
                cart_item.quantity += 1
                cart_item.save()
            return HttpResponseRedirect(reverse("cart_item"))
        elif "add_to_wishlist" in request.POST:
            user_wishlist, created = Wishlist.objects.get_or_create(user=request.user)
            print(created)
            wishlist_item, item_created = WishlistItem.objects.get_or_create(
                wishlist=user_wishlist, books=book
            )
            return HttpResponseRedirect(reverse("wishlist"))

        return HttpResponseRedirect(reverse("book_detail", kwargs={"pk": book.pk}))


class BookReviewView(LoginRequiredMixin, View):
    def post(self, request, pk):
        book = get_object_or_404(Book, pk=pk)
        user = request.user
        rating = request.POST.get("rating")
        review_text = request.POST.get("review_text")

        print(review_text)

        if not OrderItem.objects.filter(order__user=user, book=book).exists():
            messages.error(request, "You can only review books you have ordered. ")
        elif rating and review_text:
            BookReview.objects.create(
                book=book, user=user, rating=rating, review_text=review_text
            )
            book.update_avg_rating()
        return HttpResponseRedirect(reverse("book_detail", kwargs={"pk": book.pk}))


class CartView(LoginRequiredMixin, ListView):
    model = CartItem
    template_name = "cart.html"
    context_object_name = "cart_items"

    def get_queryset(self):
        try:
            user_cart = Cart.objects.get(user=self.request.user)
        except ObjectDoesNotExist:
            user_cart = Cart.objects.create(user=self.request.user)
        return CartItem.objects.filter(cart=user_cart)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        total_items = self.object_list.count()
        total_price = sum(item.books.price * item.quantity for item in self.object_list)
        context["total_items"] = total_items

        if self.request.user.order_count == 5:
            discount_price = float(total_price) - ((25 / 100) * float(total_price))

            context["discounted_price"] = discount_price

        context["total_price"] = total_price

        return context

    def post(self, request):
        otp = random.randint(1000, 9999)
        user_email = request.user.email
        send_mail(
            "OTP for Checkout",
            f"Your OTP for checkout is :{otp}",
            "anishbista9237@gmail.com",
            [user_email],
            fail_silently=False,
        )

        request.session["checkout_otp"] = otp
        return redirect("otp_confirmation")


class OTPConfirmation(View):
    def get(self, request):
        return render(request, "otp_entry.html")

    def post(self, request):
        submitted_otp = request.POST.get("otp")
        stored_otp = request.session.get("checkout_otp")

        if submitted_otp and stored_otp and int(submitted_otp) == stored_otp:
            del request.session["checkout_otp"]
            return redirect("create_order")
        else:
            error_message = "Invalid OTP. Please try again."
            return render(request, "otp_entry.html", {"error_message": error_message})


class CreateOrder(View):
    def get(self, request):
        user_cart = get_object_or_404(Cart, user=request.user)
        cart_items = CartItem.objects.filter(cart=user_cart)
        total_price = sum(item.books.price * item.quantity for item in cart_items)
        user = get_object_or_404(CustomUser, username=request.user.username)

        discount_applied = False
        if user.order_count == 5:
            discount_price = float(total_price) - (0.25 * float(total_price))
            discount_applied = True
        else:
            discount_price = total_price

        order = Order.objects.create(user=request.user, total_price=discount_price)

        if discount_applied:
            user.order_count = 0
        else:
            user.order_count += 1
        user.save()

        for item in cart_items:
            OrderItem.objects.create(
                order=order,
                book=item.books,
                quantity=item.quantity,
                price=item.books.price * item.quantity,
            )
        user_cart.cartitem_set.all().delete()

        return render(request, "checkout_success.html")


class WishlistView(LoginRequiredMixin, ListView):
    model = WishlistItem
    template_name = "wishlist.html"
    context_object_name = "wishlist"

    def get_queryset(self):
        try:
            user_wishlist = Wishlist.objects.get(user=self.request.user)

        except ObjectDoesNotExist:
            user_wishlist = Wishlist.objects.create(user=self.request.user)

        return WishlistItem.objects.filter(wishlist=user_wishlist)


class ReadBookPDFView(LoginRequiredMixin, ListView):
    model = BookPDF
    template_name = "read_book_pdf.html"
    context_object_name = "ordered_books"

    def get_queryset(self):
        user_orders = Order.objects.filter(user=self.request.user)
        print(user_orders)

        ordered_books = set()
        # Set is used so there not be two same book in collection
        for order in user_orders:
            order_items = OrderItem.objects.filter(order=order)
            # ordered_books.extend([order_items.book for order_items in order_item])
            for order_item in order_items:
                ordered_books.add(order_item.book)
        print(ordered_books)
        return ordered_books

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context["ordered_books"] = self.get_queryset()
    #     return context

    # for item in user_orders:
    #     order_items = OrderItem.objects.filter(order=item)
    #     print(item)
    #     print(order_items)
    #     for items in order_items:
    #         print(items.book.title)
    #         print(items.book.author)

    # order_item = OrderItem.objects.filter(
    #     order__user=self.request.user,
    #     book__pdf__isnull=False,
    # ).first()

    # if order_item:
    #     book_pdf = order_item.book.pdf
    #     return book_pdf
    # else:
    #     return HttpResponse(
    #         "You haven't ordered this book or PDF is not available."
    #     )

bookstore/templates/book_detail.html
<!-- templates/detail.html -->
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% load social_share %}

{% block title %}
    {{ object.title }} - Bookstore
{% endblock title %}

{% block content %}
    <div class="row">
        <div class="col-md-6">
            <img src="{{ object.image.url }}" alt="{{ object.title }}" class="img-fluid">
            <h4>Average Rating: {{object.avg_rating}} <i class="fas fa-star"></i></h4>

            <div class = "col-md-6 mt-4">
                <p >Share on Social Media:</p>
                
                <a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}" class="mx-2" target="_blank" rel="noopener noreferrer">
                    <i class="fab fa-facebook-square"></i></a>
                <a href="https://twitter.com/intent/tweet?text=Check%20out%20this%20book:%20{{ object.title }}&url={{ request.build_absolute_uri }}" class="mx-2" target="_blank" rel="noopener noreferrer">
                    <i class="fab fa-twitter-square"></i></a>
                <a href="https://www.linkedin.com/shareArticle?url={{ request.build_absolute_uri }}&title={{ object.title }}" class="mx-2" target="_blank" rel="noopener noreferrer">
                    <i class="fab fa-linkedin"></i></a>
            </div>

            <div class = "social-sharing col-md-6 mt-4">
                <h3>Share on Social Media:</h3>
                {% post_to_facebook "Book:{{object.title}} Check it out!" object_or_url "Post to Facebook"%}
                {% post_to_twitter "Book:{{object.title}}. Check it out!" object_or_url %}
                {% post_to_linkedin "Book:{{object.title}}. Check it out!" object_or_url %}
            </div>
        </div>
        <div class="col-md-6">
            <h2>{{ object.title }}</h2>
            <p><strong>Author:</strong> {{ object.author }}</p>
            <p><strong>Genre:</strong> {{ object.genre }}</p>
            <p><strong>Price:</strong> ${{ object.price }}</p>
            <p><strong>Description:</strong> {{ object.description }}</p>

            <form method="post" action="">
                {% csrf_token %}
                <button type="submit" class="btn btn-primary" name = "add_to_cart" >Add to Cart</button>
                <button type="submit" class="btn btn-primary" name = "add_to_wishlist" >Add to Wishlist</button>
            </form>
            <h3 class="mt-5">Drop Your Review</h3>
            <form method="post" action="{% url 'book_review' object.pk %}" >
                {% csrf_token %}
                {{form|crispy}}
                <button type="submit" class="btn btn-primary">Submit Review</button>
            </form>
            
            <div class="mt-5">
                
                <h3>Other Reviews</h3>
                {% if object.reviews.count > 0 %}
                    <ul>
                        {% for review in object.reviews.all %}
                            <li>
                                <strong>{{ review.user.username }}</strong> - {{review.rating}} <i class="fas fa-star"></i>
                                    <p>{{ review.review_text }}</p>
                            </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <p>No reviews yet. Be the first to review!</p>
                {% endif %} 
            </div>
            

            
            

        </div>
        
    </div>
    
{% endblock content %}

bookstore/templates/cart.html
<!-- templates/cart.html -->
{% extends 'base.html' %}

{% block title %}Bookstore - Shopping Cart{% endblock title %}

{% block content %}
    <div class="container">
        <h2>Shopping Cart</h2>
        <div class="row">
            <!-- Cart items -->
            <!-- Sample cart item -->
            <div class="col-md-8">
                {% if cart_items %}
                {% for item  in cart_items  %}
                <div class="card mb-3">
                    <div class="row g-0">
                        <div class="col-md-4">
                            <img src="{{item.books.image.url}}" class="img-fluid rounded-start" alt="Book Image">
                        </div>
                        <div class="col-md-8">
                            <div class="card-body">
                                <h5 class="card-title">{{item.books.title}}</h5>
                                <p class="card-text">{{item.books.description}}</p>
                                <p class="card-text">Quantity: {{item.quantity}}</p>
                                <p class="card-text"><small class="text-muted">${{item.books.price}}</small></p>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Repeat this structure for more cart items -->
                {% endfor %}
                {% else %}
                    <p>Your cart is empty</p>
                {% endif %}
            </div>
            
            <!-- Cart summary -->
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Cart Summary</h5>
                        <p class="card-text">Total Items: {{total_items}}</p>
                        {% if discounted_price %}
                        <p class="card-text">Previous Price: ${{total_price}}</p>
                        <p class="card-text"><i>Note: After 25% discount (For ordering 5 times)</i> 
                            </p>
                        <p class="card-text">Total Price: ${{discounted_price}}</p>
                        {% else %}
                        <p class="card-text">Total Price: ${{total_price}}</p>
                        {% endif %}

                        

                        <form action="" method="post">
                            {% csrf_token %}
                            
                            <button class="btn btn-success" type="submit">Proceed to Checkout</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

bookstore/templates/checkout_success.html
{% extends "base.html" %}
{% block title %}Bookstore- Order Success{% endblock title %}

{% block content %}

<h1>Order Successful Placed!</h1>

<a href="{% url 'index' %}">Go to Homepage</a>

{% endblock content %}

bookstore/templates/index.html
<!-- templates/index.html -->
{% extends 'base.html' %}

{% block title %}Bookstore - All Books{% endblock title %}


{% block content %}
{% if user.is_authenticated %}
<!-- Filter section -->
<div class="container mb-4">
    <h2>Filter by Genre</h2>
    <div class="row">
        <div class="col-md-3">
            <form method="GET" action="">
                <select class="form-select" name="genre" aria-label="Category" onchange="this.form.submit()">
                    <option value="">All Genre</option>
                    {% for genre_value, genre_name in genres %}
                    <option value="{{ genre_value }}" {% if request.GET.genre == genre_value %}selected{% endif %}>
                        {{ genre_name }}
                    </option>
                    {% endfor %}
                </select>
            </form>
        </div>
        <!-- Add more filters if required -->
    </div>
</div>

<!-- Book display section -->
<div class="container">
    <h2>All Books</h2>
    <div class="row">
        {% if book_list %}
        {% for book in book_list %}
        <div class="col-md-4 mb-4">
            <div class="card h-100">
                <img src="{{ book.image.url }}" class="card-img-top img-fluid" alt="Book Image">
                <div class="card-body">
                    <h5 class="card-title">{{ book.title }}</h5>
                    <p class="card-text">
                        <strong>Genre:</strong> {{ book.genre }}<br>
                        <strong>Price:</strong> ${{ book.price }}
                    </p>
                    <p class="card-text">{{ book.description | truncatechars:40 }}</p>
                    <!-- Adjust 'truncatechars:100' to limit description length -->
                    <a href="{{book.get_absolute_url }}" class="btn btn-primary">View Detail</a>
                </div>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <p>There are no books of such genre</p>
        {% endif %}
        
    </div>
</div>
{% else %}
<p>You are not logged in</p>
<a href="{% url 'login' %}">Log In</a> |
<a href="{% url 'signup' %}">Sign Up</a>
{% endif %}
{% endblock content %}

bookstore/templates/otp_entry.html
{% extends 'base.html' %}

{% block title %}OTP Confirmation - Bookstore{% endblock title %}

{% block content %}
    <div class="container">
        <h2>Enter OTP</h2>
        {% if error_message %}
        <p>{{error_message}}</p>
        {% endif %}
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <form action="{% url 'otp_confirmation' %}" method="POST">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="otpInput" class="form-label">Enter OTP</label>
                        <input type="text" class="form-control" id="otpInput" name="otp" required>
                    </div>
                    <button type="submit" class="btn btn-primary">Submit OTP</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

bookstore/templates/read_book_pdf.html
{% extends "base.html" %}

{% block title %}Read Books - Bookstore{% endblock title %}
{% block content %}
<div class="container">
    <h2>All Books</h2>
    {% comment %} {{ordered_books}} {% endcomment %}
    <div class="row">
        {% if ordered_books %}
        {% for item in ordered_books %}
        <div class="col-md-6 mb-6">
            <div class="card h-100">
                <img src="{{ item.image.url }}" class="card-img-top img-fluid" alt="Book Image">
                <div class="card-body">
                    <h5 class="card-title">{{ item.title }}</h5>
                    <h2 class="card-title">{{ item.author }}</h5>
                    
                    {% comment %} <iframe src="{{ item.pdf.pdf_file.url }}" width="100%" height="600px"></iframe> {% endcomment %}
                    <embed id="pdfEmbed" src="{{ item.pdf.pdf_file.url }}" type="application/pdf" width="100%" height="600px" target="_blank" />
                    <a href="{{ item.pdf.pdf_file.url }}" class="btn btn-primary" target="_blank">Download PDF</a>
                    <button class="btn btn-success" onclick="openFullscreen()">Open Fullscreen</button>
                    <script>
                        function openFullscreen() {
                          const elem = document.getElementById('pdfEmbed');
                          if (elem.requestFullscreen) {
                            elem.requestFullscreen();
                          } else if (elem.mozRequestFullScreen) { /* Firefox */
                            elem.mozRequestFullScreen();
                          } else if (elem.webkitRequestFullscreen) { /* Chrome, Safari & Opera */
                            elem.webkitRequestFullscreen();
                          } else if (elem.msRequestFullscreen) { /* IE/Edge */
                            elem.msRequestFullscreen();
                          }
                        }
                        </script>
                    
                    <!-- Adjust 'truncatechars:100' to limit description length -->
                    {% comment %} <a href="{{book.get_absolute_url }}" class="btn btn-primary">View Detail</a> {% endcomment %}
                </div>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <p>There are no books of such genre</p>
        {% endif %}
        
    </div>
</div>
{% endblock content %}

bookstore/templates/wishlist.html
<!-- templates/wishlist.html -->
{% extends 'base.html' %}

{% block title %}My Wishlist{% endblock title %}

{% block content %}
    <div class="container">
        <h2>My Wishlist</h2>
        {% if user.is_authenticated %}
            {% if wishlist %}
                <ul>
                    {% for item in wishlist %}
                    <div class="card mb-3" style="width: 45rem;">
                        <div class="row g-0">
                            <div class="col-md-1">
                                <img src="{{item.books.image.url}}" class="img-fluid rounded-start" id="wishlist" alt="Book Image">
                            </div>
                            <div class="col-md-3">
                                <div class="card-body">
                                    <h5 class="card-title">{{item.books.title}}</h5>
                                    <h5 class="card-title">{{item.books.author}}</h5>
                                    
                                    
                                    <p class="card-text"><small class="text-muted">${{item.books.price}}</small></p>
                                    
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </ul>
            {% else %}
                <p>Your wishlist is empty.</p>
            {% endif %}
        {% else %}
            <p>Please <a href="{% url 'login' %}">log in</a> to view your wishlist.</p>
        {% endif %}
    </div>
{% endblock content %}